### PR TITLE
Issue Fix: #513 Move dark mode toggle to nav

### PR DESCRIPTION
**Pull request by 2140data**
Referencing Issue #513 "Move dark mode toggle to nav"

I updated the Darkmode Toggle and added it to the Navbar in bitcoin-information.html. If this PR is approved, I can run through the site and add it everywhere.

Steps:

1. Added a new CSS file called "darkmodetoggle.css"
2. Added two calls in bitcoin-information.html: 1) FontAwesome (for sun/moon icons), and 2) darkmodetoggle.css
3. Deleted the old toggle and the text: "Toggle Dark Mode:"
4. Moved the updated Darkmode Toggle to the NavBar
5. Downloaded the ZIP and tested the new toggle successfully

Final Steps (if approved):

1. Delete old CSS for the old toggle
2. Populate the new toggle across all pages

### CODE REVIEW

**Comment by 2140data** [comment]
ALSO FIXING #865

Referencing Issue #865 "LN getting started"

Added "A Look at the Lightning Network" link to "Getting Started" section

**Comment by 2140data** [comment]
Screenshots of the new Toggle in action!

dark
light

**Comment by jlopp** [comment]
This is great, thanks. How does it look on the mobile nav though...

I'd like to tinker with this and implement it without needing to load additional CSS files; I should be able to do that in a week or so. I've previously used a tool to generate custom webfont files that have the icons you see in the footer; I should be able to regenerate them and add the sun / moon icons.

**Comment by 2140data** [comment]
Thank you. It looks good on mobile (see pictures), but one idea would be to keep it outside of the nav UL... so it would show the toggle at the end of the navbar on desktop, but side-by-side with the mobile nav on mobile.

I did look through the free IcoMoon set, but did not see Sun and Moon (might be paid icons, not sure).

Good news, the only CSS (besides FontAwesome call) is in the "darkmodetoggle.css" file... it's just three lines and can be added to the "styles" and "dark" stylesheets. Only downside there is: it may need to be included in both sheets vs. one (+ a call).

Bonus, the new toggle plugs into the existing javascript, there is no need to change anything there.

Happy to help!

lightmobile
darkmobile

**Comment by 2140data** [comment]
Alternate mobile option would be to show/hide it on mobile, side-by-side with the mobile nav.

For example: Desktop: display: none;  |  Mobile: display:inline;

Something like that! :)

**Comment by jlopp** [comment]
Great; looks like I've managed to optimize the CSS and get it populated across every page. Thanks!

**Pull request merged**
