### PR TITLE
Update bitcoin.html

### PR DESCRIPTION
**Pull request by 4tochka**
Blocks Explorers
  - added bitaps.com
Developer tools
 - added tbtc.bitaps.com testnet explorer + faucet
- added pybtc python library

### CODE REVIEW

**Comment by jlopp** [comment]
These all look fine, but I don't want to add more block explorers unless they are clearly superior / more popular than the existing ones. Similar issue with the python library - it doesn't look like it has developed much reputation due to how new it is. If I add a python library then it would be one that is widely used and has a larger contributor base, such as https://github.com/richardkiss/pycoin or https://github.com/ofek/bit

**Comment by 4tochka** [comment]
Ok let review for explorers in your list (sorted by alexa.com global  top rating):

- BlockCypher
    https://www.alexa.com/siteinfo/blockcypher.com
    GLOBAL RATING 30,348
- SoChain
    https://www.alexa.com/siteinfo/chain.so
    GLOBAL RATING  121,636
- Blockstream.info
    https://www.alexa.com/siteinfo/blockstream.info
      GLOBAL RATING 304,042


- Blockchain Browser and Tutorial
      (http://learnmeabitcoin.com/browser/node/)
      https://www.alexa.com/siteinfo/learnmeabitcoin.com
      GLOBAL RATING **564,479**
- Wallet Explorer
    https://www.alexa.com/siteinfo/walletexplorer.com
    GLOBAL RATING  **1,077,538**
- Apirone.com   
       https://www.alexa.com/siteinfo/apirone.com
      GLOBAL RATING  **1,769,685**
- btc.chaintools.io - open source, RPC-driven
    https://www.alexa.com/siteinfo/chaintools.io
    GLOBAL RATING .  **1,871,543**
- OXT - blockchain explorer + privacy analysis
    https://www.alexa.com/siteinfo/oxt.me
    GLOBAL RATING  **2,847,110**
- Yogh.io - raw data block explorer
    https://www.alexa.com/siteinfo/yogh.io
    GLOBAL RATING **4,409,152** 
- Blockpath Explorer + Addr/Tx Relationships
    https://www.alexa.com/siteinfo/blockpath.com
    GLOBAL RATING  **15,176,917**  


So wat about bitaps.com?

https://www.alexa.com/siteinfo/bitaps.com
GLOBAL RATING **552,474**

On april 2018 rating was < 200,000

This is 4-th place in this list!

"_unless they are clearly superior / more popular than the existing _ones._"

Also tbtc.bitaps.com is good tool for develepors with embedded testnet coins faucet.

To be honest, I don’t understand your decision.
Also half of the list does not display P2WSH, P2WPKH  addresses include BlockCypher

**Comment by jlopp** [comment]
Good point - I didn't know bitaps had been around for so long, I figured it was new. Added it with 01a3502

**Comment by 4tochka** [comment]
As far as I remember, the first time we met in Hong Kong in December 2015 on Scaling Bitcoin conference. At that time you worked bitgo, and  my English was not very good :).

**Pull request closed without merging**
