### PR TITLE
Add Other Visualizations section

### PR DESCRIPTION
**Pull request by KevinSmall**
Added new section for Other Visualizations, to cover those visualizations that are not real-time.
Added link to blockchain3d.info a 3D and VR bitcoin visualization tool

### CODE REVIEW

**Comment by jlopp** [comment]
It's weird to have a section with only one item - how about you just remove the "Realtime" from the title of the current section and add your link to it?

**Comment by KevinSmall** [comment]
Yes that makes sense I will change it

**Comment by KevinSmall** [comment]
Change made as requested in latest commit

**Comment by jlopp** [comment]
Thanks!

**Comment by KevinSmall** [comment]
Hi Jameson, thanks I see the commit was merged but I don't see the change in the live website.

Is there a delay before changes are visible?

**Comment by jlopp** [comment]
Deploying is a manual process; I've updated it now.

**Comment by KevinSmall** [comment]
Thanks Jameson it is there now :)

**Pull request merged**
