### PR TITLE
Added: 10 Million Dollar Bitcoin End Game

### PR DESCRIPTION
**Pull request by mjglqw**
Despite the title which looks like it's aimed at price speculation(it's clickbait), I think it has decent content.

### CODE REVIEW

**Comment by jlopp** [comment]
This doesn't quite fit what I'm looking for with regard to documentaries either, as this appears to be a bunch of edited clips from a variety of other shows and conferences. I think stuff in the documentaries section should be standalone productions by a single person / team.

**Comment by mjglqw** [comment]
Fair enough. Aren't you planning on adding a "debates" section?

**Comment by jlopp** [comment]
No plans at the moment; the debates I've seen tend not to be good educational content because they're often time limited and end up glossing over a lot of nuance.

**Comment by mjglqw** [comment]
Understandable. Hit me up if you ever plan on having a section for it. I have a small list of debates(a dozen).

**Pull request closed without merging**
